EWB-1798: Support including linked containers in get_equipment_for_container(s)
zepben/evolve-sdk-python pull request #106
Opened 2022-08-18 03:18 UTC by Lax125

2022-08-18 03:18 UTC, ryanjcoleman commented
Task linked: [EWB-1798 Update Python SDK](https://app.clickup.com/t/6929263/EWB-1798)

2022-08-18 03:19 UTC, Lax125 commented
- [ ] Accept https://github.com/zepben/evolve-grpc/pull/58

2022-08-29 00:55 UTC, Lax125 commented
- [ ] Rebase onto main after https://github.com/zepben/evolve-sdk-python/pull/104 gets merged

2022-08-31 05:14 UTC, charlta requested changes

2022-08-31 05:14 UTC, charlta commented on test/streaming/get/test_network_consumer.py
> +    async def test_get_equipment_for_containers(self, feeder_network: NetworkService):
todo: test name has already been used so replaces the above test. Please rename the tests to something appropriate.

2022-09-04 23:42 UTC, charlta approved these changes

2022-09-04 23:42 UTC, merged