EWB-2500: Support protection equipment
zepben/evolve-sdk-python pull request #123
Opened 2023-01-06 06:51 UTC by Lax125

# Description

Implements model change to support protection equipment. See https://app.clickup.com/t/6929263/EWB-2473 for the spec.

# Associated tasks:

List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.

# Checklist:

- [ ] I have performed a self review of my own code.
- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
- [ ] I have updated the changelog.
- [ ] I have updated any documentation required for these changes.
- [ ] I have commented my code in any hard-to-understand or hacky areas.
- [ ] I have handled all new warnings generated by the compiler or IDE.
- [ ] I have considered if this is a breaking change and have communicated it with other team members if so.

2023-01-06 06:51 UTC, ryanjcoleman commented
Task linked: [EWB-2473 Data model change spec](https://app.clickup.com/t/6929263/EWB-2473)

2023-01-06 06:51 UTC, ryanjcoleman commented
Task linked: [EWB-2500 Update Python SDK](https://app.clickup.com/t/6929263/EWB-2500)

2023-01-09 00:43 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/protection/current_relay.py
> +        return self.asset_info
This is a type strengthening property, like `ShuntCompensator.shunt_compensator_info`.

2023-01-09 00:43 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/protection/current_relay.py
> +        return self.asset_info
@sonatype-lift ignore

2023-01-09 00:51 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/protection/protection_equipment.py
> +    def __init__(self, protected_switches: Iterable[ProtectedSwitch] = None, **kwargs):
For whatever reason, `Optional` is omitted in `__init__` for optional parameters in this repo. On one hand it discourages manually setting the param to `None` which has no effect, but on the other hand it makes it less clear that the parameter is optional. @kgreav your thoughts?

2023-01-09 01:16 UTC, Lax125 commented on src/zepben/evolve/services/common/reference_resolvers.py
> +current_relay_to_current_relay_info_resolver = ReferenceResolver(CurrentRelay, CurrentRelayInfo, lambda t, r: setattr(t, 'asset_info', r))
Is a `dataclassy.dataclass`

2023-01-09 01:16 UTC, Lax125 commented on src/zepben/evolve/services/common/reference_resolvers.py
> +current_relay_to_current_relay_info_resolver = ReferenceResolver(CurrentRelay, CurrentRelayInfo, lambda t, r: setattr(t, 'asset_info', r))
@sonatype-lift ignore

2023-01-09 01:17 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/wires/switch.py
> +        return self.asset_info
This is a type strengthening property, like `ShuntCompensator.shunt_compensator_info`.

2023-01-09 01:17 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/wires/switch.py
> +        return self.asset_info
@sonatype-lift ignore

2023-01-09 01:18 UTC, Lax125 commented on src/zepben/evolve/database/sqlite/tables/associations/protection_equipment_protected_switches.py
> +    protection_equipment_mrid: Column = None
`dataclassy` needs a default value to use as a factory.

2023-01-09 01:18 UTC, Lax125 commented on src/zepben/evolve/database/sqlite/tables/associations/protection_equipment_protected_switches.py
> +    protection_equipment_mrid: Column = None
@sonatype-lift ignore

2023-01-16 10:45 UTC, Lax125 commented
Sorry for the late update, some minor fixes to some test names along with adding missing `await`s.

2023-01-17 10:18 UTC, kgreav requested changes
Nice work, only things I can see you've missed is updating `test_network_service_comparator.py` and the changelog update.

2023-01-18 02:18 UTC, Lax125 commented on changelog.md
>  ### New Features
Added notes.

2023-01-18 02:23 UTC, Lax125 commented on src/zepben/evolve/database/sqlite/readers/network_cim_reader.py
> +        switch_info = SwitchInfo(mrid=set_last_mrid(rs.get_string(table.mrid.query_index)))
`get_string` raises by default

2023-01-18 02:24 UTC, Lax125 commented on src/zepben/evolve/database/sqlite/readers/network_cim_reader.py
> +        switch_info = SwitchInfo(mrid=set_last_mrid(rs.get_string(table.mrid.query_index)))
@sonatype-lift ignore

2023-01-18 05:54 UTC, kgreav approved these changes

2023-01-18 05:54 UTC, merged