EWB-3763 Protection extensions
zepben/evolve-sdk-python pull request #147
Opened 2024-03-20 05:46 UTC by vincewhite

# Description

The python implementation of EWB-3757 (Protection model change) https://github.com/zepben/evolve-sdk-jvm/pull/158

# Associated tasks

The jvm-sdk implementation: https://github.com/zepben/evolve-sdk-jvm/pull/158

Requires: https://github.com/zepben/evolve-grpc/pull/84 v0.27.0?

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [~] I have performed a self review of my own code (including checking issues raised when creating the PR).
- [x] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
- [x] I have commented my code in any hard-to-understand or hacky areas.
- [x] I have handled all new warnings generated by the compiler or IDE.
- [x] I have rebased onto the target branch (usually main).
      
### Documentation
- [~] I have updated the changelog.
- [x] I have updated any documentation required for these changes.

# Breaking Changes
- [x] I have considered if this is a breaking change and will communicate it with other team members if so.

* Removed `ProtectionEquipment`.
* Change of inheritance: `CurrentRelay` &rarr; `ProtectionEquipment`.
  becomes `CurrentRelay` &rarr; `ProtectionRelayFunction`.
* Removed symmetric relation `ProtectionEquipment` &harr; `ProtectedSwitch`.
* Renamed `CurrentRelayInfo` to `RelayInfo`.
  * The override `CurrentRelay.relay_info` has been moved from `CurrentRelay` to its new parent class, `ProtectionRelayFunction`.
  * Renamed `RelayInfo.remove_delay` to `RelayInfo.remove_delay_at`. The original method name has been repurposed to remove a delay by its value rather than its
    index.
* Reworked values for enumerable type `ProtectionKind`.

# Other Things I Touched
Since `test.services.common.service_comparator_validator.ServiceComparatorValidator` now has the ability to handle expected side effects when validating the properties of objects via the `expected_differences` parameter. 

I updated the `NetworkServiceComparator` to include the properties that "override" `asset_info`  e.g. `ProtectionRelayFunction.relay_info` or `PowerTransformerInfo.power_transformer_info`. 

This also included updating `ServiceComparatorValidator` to test/validate comparing these properties and their expected side effects on `asset_info`(and vice versa).

2024-03-20 05:46 UTC, ryanjcoleman commented
Task linked: [EWB-3763 Update Python SDK](https://app.clickup.com/t/6929263/EWB-3763)

2024-03-20 05:46 UTC, ryanjcoleman commented
Task linked: [EWB-3757 Update JVM SDK](https://app.clickup.com/t/6929263/EWB-3757)

2024-03-25 02:44 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/wires/power_transformer.py
> +                    lambda: f"Cannot assign {self.__class__.__name__}[{self.mrid}] to {value.__class__.__name__}[{value.mrid}], which is connected to a " +
yep

2024-03-25 03:03 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/protection/protection_relay_function.py
> +    def add_threshold(self, threshold: RelaySetting, sequence_number: int = None) -> ProtectionRelayFunction:
They mean the same thing, but for some reason terminals are 1-indexed. Not sure how it ended up that way, I just copied how it works with locations and position points.

2024-03-25 03:07 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/protection/protection_relay_function.py
> +        require(0 <= sequence_number <= self.num_thresholds(),
I don't see a use case for that. The order only matters for matching up with the time limits (e.g. 5A for 2 seconds, 10A for 0.1 seconds)

2024-03-25 03:39 UTC, Lax125 commented on src/zepben/evolve/database/sqlite/readers/network_cim_reader.py
> +        value = rs.get_double(table.value.query_index)
Maybe require a non-nan value in `RelaySetting.__init__(self)`? Similar to `PositionPoint.__init__(self)`

2024-03-25 04:15 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/protection/protection_relay_function.py
> +            raise ValueError(f"Error initializing {self.__class__.__name__}[{self.mrid}]. time_limits and thresholds must be initialized together.")
I don't think it should. The user should be able to specify the thresholds first and add time limits later or vice-versa.

2024-03-25 05:00 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/protection/protection_relay_function.py
> +        # TODO: raise index error or return None, see RelayInfo.get_delay()
raise index error

2024-03-26 01:33 UTC, Lax125 requested changes
Praise: all in all very thorough. Thanks for adding missing stuff for current/voltage transformers and LV feeders.

2024-03-26 01:33 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/protection/relay_setting.py
> +
Nit: Final line should be empty (no spaces/tabs even)

2024-03-26 02:58 UTC, Lax125 commented on src/zepben/evolve/model/cim/iec61970/base/protection/distance_relay.py
> +    operation_phase_angle3: Optional[float] = None
Could you do the same for the table class as well (`TableDistanceRelays`)?

2024-03-26 03:27 UTC, Lax125 commented on setup.py
> +    "zepben.protobuf==0.27.0b5",
Version checks out

2024-03-26 03:27 UTC, Lax125 submitted a review, later dismissed

2024-03-27 01:18 UTC, kgreav submitted a review, later dismissed

2024-03-27 10:56 UTC, kgreav approved these changes

2024-03-27 11:03 UTC, merged