[PROJ-480] Update SDK to accept token
zepben/evolve-sdk-python pull request #42
Opened 2021-05-05 04:39 UTC by clydeu

2021-05-05 04:39 UTC, ryanjcoleman commented
Task linked: [PROJ-480 Update SDK to accept token](https://app.clickup.com/t/6929263/PROJ-480)

2021-05-20 01:26 UTC, ramonbouckaert commented
Updated to use the EWBAuthenticator class provided by zepben.auth available here https://bitbucket.org/zepben/zepben-auth-python/

2021-05-20 04:18 UTC, kgreav requested changes

2021-05-20 04:18 UTC, kgreav commented on src/zepben/evolve/streaming/grpc/connect.py
> +        if self.conf_address and datetime.utcnow().timestamp() > self.token_expiry:
this should probably be an elif, just in case someone provides conf_address and an authenticator.

2021-05-20 04:18 UTC, kgreav commented on src/zepben/evolve/streaming/grpc/connect.py
> +            authenticator=None):
can you just add authenticator to the docstring below, as well as on `connect_async`?

also note that authenticator will be preferred if it's provided over client creds

2021-05-20 04:42 UTC, merged