Add username and password authentication option to connect_async
zepben/evolve-sdk-python pull request #59
Opened 2021-08-18 17:30 UTC by ramonbouckaert

This is a common use case in all the sdk demos, so instead of making the end user jump through hoops and define and pass in their own `ZepbenAuthenticator`, they can simply pass in a `username` and `password` instead, and the appropriate authenticator will be constructed for them.

2021-08-18 23:30 UTC, gcarwardine commented
@ramonbouckaert @kgreav it's not high priority but should any of these auth changes also be made within the jvm SDK or auth libs? If so I want to get it tasked up so it's on our radar and not forgotten.

2021-08-19 00:00 UTC, kgreav requested changes

2021-08-19 00:08 UTC, kgreav commented
@gcarwardine yes can you create two tasks
1. Create ZepbenAuthenticator in zepben-auth (jvm) based on python implementation
2. Deprecate JwtCredentials from evolve-sdk-jvm and replace with ZepbenAuthenticator (should match python SDK)
3. Support username+password auth in jvm sdk

It will need to be done prior to 1.0

2021-08-19 00:22 UTC, kgreav approved these changes

2021-08-19 00:24 UTC, merged