Add StreetDetail
zepben/evolve-sdk-python pull request #74
Opened 2022-01-20 05:07 UTC by Lax125

Signed-off-by: Marcus Koh <marcus.koh@zepben.com>

2022-01-20 05:07 UTC, ryanjcoleman commented
Task linked: [EWB-1069 Update StreetAddress in Python SDK](https://app.clickup.com/t/6929263/EWB-1069)

2022-01-20 05:10 UTC, Lax125 commented
Issues possibly arising from new protobuf version. Will look into it.

2022-01-20 05:25 UTC, Lax125 commented
Having an issue with multiple inheritance here too (deja vu...)
I'll work on it tomorrow.

2022-01-20 06:21 UTC, Lax125 commented
After stepping away from the code, I'm now considering just merging all the fields from `TableStreetDetails` and `TableTownDetails` into `TableStreetAddresses`. I already did it for `TableStreetDetails` in the jvm sdk and all usages of `TableStreetDetails` and `TableTownDetails` seem to be a part of a more monolithic action on a `TableStreetAddresses`.

2022-01-20 23:49 UTC, Lax125 commented
I wonder if it would be better to rename the columns to be more specific (e.g. type -> street_type) for both sdks.

2022-01-24 04:18 UTC, Lax125 commented
Will go over the changes on the jvm version.

2022-01-25 02:40 UTC, charlta requested changes
I will push some changes and a test that fails to reveal an issue with PR. Can you please fix so the test passes and also add tests for the `TownDetail` and `StreetDetails` empty checks (as per JVM)

2022-01-25 09:47 UTC, charlta commented on test/services/network/translator/test_network_translator.py
> +from test.database.sqlite.schema_utils import assume_non_blank_street_address_details
Good catch on the import. This is my pet peeve as the import works in the IDE without the `test.` so I constantly miss it.

2022-01-25 09:48 UTC, charlta approved these changes

2022-01-25 09:49 UTC, merged